#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ `basename $0` = 'nodeprobe' ]; then
    echo "***************************************************************" >&2
    echo "WARNING: $0 is obsolete, use `dirname $0`/nodetool instead" >&2
    echo "***************************************************************" >&2
fi

if [ "x$SOLANDRA_INCLUDE" = "x" ]; then
    for include in /usr/share/solandra/solandra.in.sh \
                   /usr/local/share/solandra/solandra.in.sh \
                   /opt/solandra/solandra.in.sh \
                   `dirname $0`/solandra.in.sh; do
        if [ -r $include ]; then
            . $include
            break
        fi
    done
elif [ -r $SOLANDRA_INCLUDE ]; then
    . $SOLANDRA_INCLUDE
fi

# Use JAVA_HOME if set, otherwise look for java in PATH
if [ -x $JAVA_HOME/bin/java ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA=`which java`
fi

if [ -z $SOLANDRA_CONF -o -z $CLASSPATH ]; then
    echo "You must set the SOLANDRA_CONF and CLASSPATH vars" >&2
    exit 1
fi

# Special-case path variables.
case "`uname`" in
    CYGWIN*) 
        CLASSPATH=`cygpath -p -w "$CLASSPATH"`
        SOLANDRA_CONF=`cygpath -p -w "$SOLANDRA_CONF"`
    ;;
esac

$JAVA -cp $CLASSPATH -Dstorage-config=$SOLANDRA_CONF \
        -Dlog4j.configuration=log4j-tools.properties \
        org.apache.cassandra.tools.NodeCmd $@

# vi:ai sw=4 ts=4 tw=0 et
